// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GuildConfig struct {
	GuildID     string
	World       string
	TibiaGuilds []string
	UpdatedAt   pgtype.Timestamp
}

type Player struct {
	Name      string
	Level     int32
	World     string
	UpdatedAt pgtype.Timestamp
}
