CREATE TABLE IF NOT EXISTS guild_configs (
    guild_id VARCHAR(32) PRIMARY KEY,
    world VARCHAR(64) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
    name VARCHAR(64) PRIMARY KEY,
    level INT NOT NULL,
    world VARCHAR(64) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
